FROM radiolab_og

ARG DEBIAN_FRONTEND="noninteractive"

####################
####    AFNI    ####
####################
ENV AFNI_VERSION="ubuntu_16_64"
RUN echo "options(Ncpus = $(echo "$(nproc)-2" | bc)L)" > /root/.Rprofile \
    && echo "Installing AFNI ..." \
    && mkdir -p /opt/afni \
    && curl -fSL --retry 5 https://afni.nimh.nih.gov/pub/dist/tgz/linux_${AFNI_VERSION}.tgz \
        | tar -xz -C /opt/afni --strip-components 1 \
    && PATH=$PATH:/opt/afni rPkgsInstall -pkgs ALL \
    && rm /root/.Rprofile