FROM radiolab_og

ARG DEBIAN_FRONTEND="noninteractive"

####################
####   MRtrix   ####
####################
RUN echo "Installing MRtrix3 ..." \
    && git clone https://github.com/3Tissue/MRtrix3Tissue.git /opt/3Tissue \
    && cd /opt/3Tissue \
    && ./configure \
    && ./build \
    && git clone https://github.com/MRtrix3/mrtrix3.git /opt/mrtrix3 \
    && cd /opt/mrtrix3 \
    && ./configure \
    && ./build
ENV PATH="/opt/mrtrix3/bin:/opt/3Tissue/bin:$PATH"