#ubuntu:20.04
FROM ubuntu:20.04
# mesa runtime
ARG DEBIAN_FRONTEND=noninteractive
ENV NV_RUNTIME=0 \
    BASE="ubuntu:20.04"
# CN_SP+
RUN sed -i "s/archive.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list
# CN_SP-
# OpenGL and glvnd
RUN yes | unminimize \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
            libxext6 \
            libx11-6 \
            libglvnd0 \
            libgl1 \
            libglx0 \
            libegl1 \
            freeglut3-dev \
            mesa-utils \
            qt5-default \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*