# syntax = docker/dockerfile:experimental
FROM radiolab_og

ARG DEBIAN_FRONTEND="noninteractive" \
    AFNI_VERSION \
    FSL_VERSION \
    FREESURFER_VERSION \
    DCM2NIIX_VERSION
ENV AFNI_VERSION=${AFNI_VERSION} \
    FSL_VERSION=${FSL_VERSION} \
    FREESURFER_VERSION=${FREESURFER_VERSION} \
    DCM2NIIX_VERSION=${DCM2NIIX_VERSION}}

####################
####    AFNI    ####
####################
RUN --mount=type=bind,from=radiolab_afni,target=/tmp/opt/,source=/opt \
     cp -rf /tmp/opt/* /opt/
RUN --mount=type=bind,from=radiolab_afni,target=/tmp/R,source=/usr/local/lib/R/site-library \
     mkdir -p /usr/local/lib/R/site-library/ && cp -rf /tmp/R/* /usr/local/lib/R/site-library/
# ####################
# ####    ANTs    ####
# ####################
# copy ants from old build, because kitware use sha256 instead of md5 which causing ants build failure
RUN --mount=type=bind,from=radiolab,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/ants /opt/
# ####################
# ####     FSL    ####
# ####################
RUN --mount=type=bind,from=radiolab_fsl,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
# ####################
# #### Freesurfer ####
# ####################
RUN --mount=type=bind,from=radiolab_freesurfer,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
# ####################
# ####  dcm2niix  ####
# ####################
RUN --mount=type=bind,from=radiolab_dcm2niix,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
# ####################
# #### miniconda  ####
# ####################
RUN --mount=type=bind,from=radiolab_miniconda,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/

####################
#### Post Setup ####
####################
RUN mkdir /opt/bash_config
COPY SRC/bashrc /opt/bash_config/bashrc
RUN sed -i -e '$c if [ -n "$1" ]; then "$@"; else /usr/bin/env bash --rcfile /opt/bash_config/bashrc; fi' $RD_ENTRYPOINT \
    && echo '# Activate "radioconda"' >> /opt/bash_config/bashrc \
    && echo 'source activate radioconda' >> /opt/bash_config/bashrc

####################
#### Sys Update ####
####################
ARG SYS_BUILD_DATE
ENV SYS_BUILD_DATE=${SYS_BUILD_DATE}
RUN apt-get update -qq \
    && apt-get upgrade -qq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# ####################
# ####  Personal  ####
# ####################
# RUN apt-get update -qq \
#     && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
#     && apt-get install -y -q --no-install-recommends \
#         neovim \
#         nodejs \
#     && apt-get install -f \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*