# nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04
FROM nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04
# nvidia-container-runtime
ARG DEBIAN_FRONTEND=noninteractive
ENV NV_RUNTIME=1 \
    BASE="nvidia/11.4.2-cudnn8-runtime-ubuntu20.04" \
    NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all} \
    NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics
# CN_SP+
RUN sed -i "s/archive.ubuntu.com/mirrors.ustc.edu.cn/g" /etc/apt/sources.list \
    && echo "deb https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2004/x86_64/ ./" > /etc/apt/sources.list.d/cuda.list
# CN_SP-
# OpenGL and glvnd
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
            libxext6 \
            libx11-6 \
            libglvnd0 \
            libgl1 \
            libglx0 \
            libegl1 \
            freeglut3-dev \
            mesa-utils \
            qt5-default \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*