# syntax = docker/dockerfile:experimental
FROM radiolab_docker_custom

ARG DEBIAN_FRONTEND="noninteractive"
####################
####  Personal  ####
####################
RUN apt-get update -qq \
    && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y -q --no-install-recommends \
        neovim \
        nodejs \
        universal-ctags \
        jags \
        glpk-utils \
    && apt-get install -f \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
