FROM radiolab_og

ARG DEBIAN_FRONTEND="noninteractive" \
    ALL_PROXY

####################
#### miniconda  ####
####################

####################
#### numpy      ####
#### pandas     ####
#### scipy      ####
#### matplotlib ####
#### seaborn    ####
#### sk-learn   ####
#### tensorflow ####
#### pytorch    ####
#### pydicom    ####
#### nipype     ####
#### graphviz   ####
#### pydot      ####
#### nibabel    ####
#### pybids     ####
#### qsiprep    ####
#### amico      ####
#### dipy       ####
#### nilearn    ####
####################

ENV PATH="/opt/miniconda-latest/bin:$PATH"
RUN echo "Installing Miniconda ..." \
    && conda_installer="/tmp/miniconda.sh" \
    && curl -fsSL --retry 5 -o "$conda_installer" https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && bash "$conda_installer" -b -p /opt/miniconda-latest \
    && rm -f "$conda_installer" \
    && conda update -yq -nbase conda \
    && conda config --system --prepend channels conda-forge \
    && conda config --system --set auto_update_conda false \
    && conda config --system --set show_channel_urls true \
    && sync && conda clean -y --all && sync \
    && ALL_PROXY="" conda create -y -q --name radioconda python=3.7 \
    && if [ ${NV_RUNTIME} -eq 1 ]; then \
            TF="tensorflow-gpu";\
        else \
            TF="tensorflow"; \
        fi \
    && bash -c "source activate radioconda \
    && ALL_PROXY="" pip install pysocks \
    &&   pip install --no-cache-dir  \
             "numpy" \
             "pandas" \
             "scipy" \
             "pandoc" \
             "matplotlib" \
             "seaborn" \
             "jupyterlab" \
             "ipywidgets" \
             "scikit-learn" \
             "scikit-image==0.16.2" \
             "${TF}" \
             "pydicom" \
             "nipype[all]" \
             "graphviz" \
             "pydot"   \
             "nibabel" \
             "pybids" \
             "bids-validator" \
             "git+https://github.com/PennLINC/qsiprep.git" \
             "sentry-sdk" \
             "cvxpy" \
             "dcm2bids" \
             "dmri-amico" \
             "dipy" \
             "vtk==8.1.2" \
             "fury" \
             "nilearn" \
             " \
    && rm -rf ~/.cache/pip/* \
    && rm -rf ~/.condarc \
    && rm -rf ~/.config/pip/pip.conf \
    && sync
