FROM radiolab_og

ARG DEBIAN_FRONTEND="noninteractive"

####################
####     FSL    ####
####################
RUN echo "Installing FSL ..." \
    && mkdir /opt/fsl \
    && curl -fSL --retry 5 https://fsl.fmrib.ox.ac.uk/fsldownloads/fsl-${FSL_VERSION}-centos7_64.tar.gz \
     | tar -xz -C /opt/fsl --strip-components 1 \
    && echo "Installing FSL conda environment ..." \
    && bash /opt/fsl/etc/fslconf/fslpython_install.sh -f /opt/fsl \
    && sed -i '$isource $FSLDIR/etc/fslconf/fsl.sh' $RD_ENTRYPOINT \
    && echo "Getting neurolabusc's fsl_sub for a better parallel computing experience ..." \
    && git clone https://github.com/neurolabusc/fsl_sub /opt/fsl_sub \
    && rm /opt/fsl/bin/fsl_sub \
    && chmod a+x /opt/fsl_sub/fsl_sub \
    && ln -s /opt/fsl_sub/fsl_sub /opt/fsl/bin/fsl_sub