# syntax = docker/dockerfile:experimental
FROM radiolab_og

####################
####    ENVs    ####
####################
ARG DEBIAN_FRONTEND="noninteractive" \
    AFNI_VERSION \
    FSL_VERSION \
    FREESURFER_VERSION \
    DCM2NIIX_VERSION
ENV AFNI_VERSION=${AFNI_VERSION} \
    FSL_VERSION=${FSL_VERSION} \
    FREESURFER_VERSION=${FREESURFER_VERSION} \
    DCM2NIIX_VERSION=${DCM2NIIX_VERSION}} \
    C3D_VERSION=${C3D_VERSION} \
    PATH="/opt/miniconda-latest/bin:/opt/c3d/bin:/opt/dcm2niix:/opt/freesurfer/bin:/opt/fsl/bin:/opt/ants/bin:/opt/ants/Scripts:/opt/dsi-studio:/opt/mrtrix3/bin:/opt/afni:$PATH" \
####################
####    AFNI    ####
####################
    AFNI_PLUGINPATH="/opt/afni"\
    QT_X11_NO_MITSHM=1 \
####################
####    ANTs    ####
####################
    ANTSPATH="/opt/ants/bin" \
####################
####     FSL    ####
####################
    FSLDIR="/opt/fsl" \
    FSLOUTPUTTYPE="NIFTI_GZ" \
    FSLMULTIFILEQUIT="TRUE" \
    FSLTCLSH="/opt/fsl/bin/fsltclsh" \
    FSLWISH="/opt/fsl/bin/fslwish" \
    FSLLOCKDIR="" \
    FSLMACHINELIST="" \
    FSLREMOTECALL="" \
    FSLGECUDAQ="cuda.q" \
####################
#### Freesurfer ####
####################
    OS="Linux" \
    FS_OVERRIDE=0 \
    FIX_VERTEX_AREA="" \
    FSF_OUTPUT_FORMAT="nii.gz" \
    FREESURFER_HOME="/opt/freesurfer" \
    LD_LIBRARY_PATH="/opt/freesurfer/lib/qt/lib:$LD_LIBRARY_PATH" \
####################
####  dcm2niix  ####
####################
#### NO SETTING ####
####################
#
####################
####itk_snap c3d####
####################
    C3D_HOME="/opt/c3d" \
#
####################
#### miniconda  ####
####################
    CONDA_DIR="/opt/miniconda-latest"
####################

####################
####    Copy    ####
####################
####################
####    AFNI    ####
####################
RUN --mount=type=bind,from=radiolab_afni,target=/tmp/opt/,source=/opt \
     cp -rf /tmp/opt/* /opt/
RUN --mount=type=bind,from=radiolab_afni,target=/tmp/R,source=/usr/local/lib/R/site-library \
     mkdir -p /usr/local/lib/R/site-library/ && cp -rf /tmp/R/* /usr/local/lib/R/site-library/
####################
####    ANTs    ####
####################
RUN --mount=type=bind,from=radiolab_ants,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/ants /opt/
####################
####  MRtrix3   ####
####################
RUN --mount=type=bind,from=radiolab_mrtrix,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/mrtrix3 /opt/
####################
#### DSI Studio ####
####################
RUN --mount=type=bind,from=radiolab_dsistudio,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/dsi-studio /opt/
####################
####     FSL    ####
####################
RUN --mount=type=bind,from=radiolab_fsl,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
####################
#### Freesurfer ####
####################
RUN --mount=type=bind,from=radiolab_freesurfer,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
####################
####  dcm2niix  ####
####################
RUN --mount=type=bind,from=radiolab_dcm2niix,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
####################
####  Convert3D ####
####################
RUN --mount=type=bind,from=radiolab_c3d,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
####################
#### miniconda  ####
####################
RUN --mount=type=bind,from=radiolab_miniconda,target=/tmp/opt/,source=/opt \
    cp -rf /tmp/opt/* /opt/
####################

####################
#### Post Setup ####
####################
RUN mkdir /opt/bash_config
COPY SRC/bashrc /opt/bash_config/bashrc
RUN sed -i -e '$c if [ -n "$1" ]; then "$@"; else /usr/bin/env bash --rcfile /opt/bash_config/bashrc; fi' $RD_ENTRYPOINT \
    && echo '# Activate "radioconda"' >> /opt/bash_config/bashrc \
    && echo 'source activate radioconda' >> /opt/bash_config/bashrc

####################
#### Sys Update ####
####################
ARG SYS_BUILD_DATE
ENV SYS_BUILD_DATE=${SYS_BUILD_DATE}
RUN apt-get update -qq \
    && apt-get upgrade -qq \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# ####################
# ####  Personal  ####
# ####################
# RUN apt-get update -qq \
#     && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
#     && apt-get install -y -q --no-install-recommends \
#         neovim \
#         nodejs \
#     && apt-get install -f \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*