FROM radiolab_og

ARG DEBIAN_FRONTEND="noninteractive"

####################
#### Freesurfer ####
####################
ENV	FREESURFER_VERSION="7.2.0" \
    FREESURFER_HOME="/opt/freesurfer"
RUN echo "Installing FreeSurfer ..." \
    && mkdir -p /opt/freesurfer \
    && curl -fSL --retry 5 https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/${FREESURFER_VERSION}/freesurfer-linux-centos8_x86_64-${FREESURFER_VERSION}.tar.gz \
     | tar -xz -C /opt/freesurfer --strip-components 1 \
    && echo "Installing MCR2014(v84) just for FreeSurfer......" \
    && mkdir /tmp/MCRv84 \
    && cd /tmp/MCRv84 \
    && MCR_URL=https://ssd.mathworks.cn/supportfiles/downloads/R2014b/deployment_files/R2014b/installers/glnxa64/MCR_R2014b_glnxa64_installer.zip \
#CN_SP+
    && sed -i -e "s/com/cn/g" /opt/freesurfer/bin/fs_install_mcr \
#CN_SP-
    && curl ${MCR_URL} -o install.zip \
    && unzip install.zip \
    && ./install -mode silent -agreeToLicense yes -destinationFolder /tmp/MCRv84 \
    && mv /tmp/MCRv84/v84 ${FREESURFER_HOME}/MCRv84 \
    && cd /tmp && rm -rf /tmp/MCRv84 \
    && sed -i '$isource "/opt/freesurfer/SetUpFreeSurfer.sh"' "$RD_ENTRYPOINT"
ENV PATH="/opt/freesurfer/bin:$PATH"